kmdah:
  mangadex:
    client-secret: super-very-mega-secret
    graceful-shutdown-seconds: 300

  operator:
    port: 3000
    ping-frequency-seconds: 30
    workers-uri: https://my-load-balancer-hostname.com
    tls-secret:
      namespace: default
      name: mangadex-at-home-tls-secret

  worker:
    port: 3001
    operator-uri: http://operator:3000
    bandwidth-mbps: 100
    verify-referrer: true

  cache:
    root: cache
    size-gib: 10
