kmdah:

  operator:
    port: 3000
    secret: senpainonono

  tls-secret:
    namespace: mdah
    name: tls-secret

  load-balancer:
    uri: mdah.tristan.moe

  worker:
    port: 3001
    operator-uri: http://kmdah-operator.mdah.svc.cluster.local:3000
    bandwidth-mbps: 200

  database:
    host: http://pgsql.default.svc.cluster.local
    port: 25555
    database: mdah
    user: mdah
    password: k8s-tan_1234

  cache:
    root: /mangahome/cache
    max-size-gibibytes: 200
