# This example is not suitable for usage in live clients
# indeed it completely ignores SSL termination, and is rather meant for
# development and testing purposes
---
version: "3.8"

services:
  redis:
    container_name: kmdah_redis
    image: library/redis:6-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200M'

  mongo:
    container_name: kmdah_mongo
    image: library/mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: kmdah
      MONGO_INITDB_ROOT_PASSWORD: kmdah
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
