version: "3.8"

services:
  mongo:
    image: library/mongo:4.4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kmdah
      MONGO_INITDB_ROOT_PASSWORD: kmdah
    networks:
      - kmdah-test
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'

  redis:
    image: library/redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - kmdah-test
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200M'

  kmdah:
    depends_on: [ mongo, redis ]
    image: tristandeloche/kmdah:latest
    ports:
      - 8080:8080
    environment:
      KMDAH_MANGADEX_CLIENT_SECRET: "${KMDAH_MANGADEX_CLIENT_SECRET}"
      KMDAH_CACHE_MONGODB_HOST: "mongo"
      KMDAH_GOSSIP_REDIS_HOST: "redis"
      KMDAH_K8S_TLS_SECRET_AUTO_UPDATE: "false"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
    networks:
      - kmdah-test

networks:
  kmdah-test:
    name: kmdah-test
