version: "3.8"

services:
  lss3:
    image: localstack/localstack:latest
    container_name: lss3
    ports:
      - 5002:5002
      - 9999:8080
    environment:
      - SERVICES=s3
      - S3_PORT=5002
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/lss3/data

  operator:
    image: tristandeloche/kmdah-operator:0.0.1-SNAPSHOT
    container_name: operator
    depends_on: [ lss3 ]
    ports:
      - 3000:3000
    environment:
      - KMDAH_CONFIG_FILE="/config/configuration.yml"
    volumes:
      - type: bind
        source: ./configuration-sample.yml
        target: /config/configuration.yml
        read_only: true

  worker:
    image: tristandeloche/kmdah-worker:0.0.1-SNAPSHOT
    container_name: worker
    depends_on: [ operator ]
    ports:
      - 3001:3001
    environment:
      - KMDAH_CONFIG_FILE="/config/configuration.yml"
    volumes:
      - type: bind
        source: ./configuration-sample.yml
        target: /config/configuration.yml
        read_only: true
