spring:
  application.name: kmdah-operator

  profiles.include:
    - ${KMDAH_PROFILE:prod}
    - kmdah

  liquibase:
    change-log: classpath:db/changesets.xml
    liquibase-schema: public
    default-schema: public

  task.scheduling.pool.size: 4

server.port: ${kmdah.operator.port}
