# Internal configuration
spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    spec: @mangadex.spec@

  data:
    mongodb:
      host: ${kmdah.cache.mongodb.host}
      port: ${kmdah.cache.mongodb.port}
      authentication-database: ${kmdah.cache.mongodb.authentication-database}
      username: ${kmdah.cache.mongodb.username}
      password: ${kmdah.cache.mongodb.password}

  redis:
    host: ${kmdah.gossip.redis.host}
    port: ${kmdah.gossip.redis.port}

  config:
    import: optional:file:${KMDAH_CONFIGURATION:config.yml}
  profiles:
    active: ${kmdah.cache.backend}

server:
  port: ${kmdah.worker.port}
  shutdown: graceful
  forward-headers-strategy: framework
  server-header: "kmdah ${spring.application.version} (${spring.application.spec}) - github.com/Tristan971/kmdah"
  jetty:
    threads.idle-timeout: 15s
    connection-idle-timeout: 15s

logging.level:
  root: WARN
  moe.tristan.kmdah: INFO
  org.springframework:
    boot.web.embedded.jetty: INFO
    integration.leader: INFO

management:
  endpoint.health.show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /__mon
      exposure.include:
        - info
        - health
        - prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            percentiles: 0.5,0.75,0.9,0.95,0.99,0.999
      client:
        request:
          autotime:
            percentiles: 0.5,0.75,0.9,0.95,0.99,0.999

# User configuration
kmdah:

  cache:
    backend: ${KMDAH_CACHE_BACKEND:cache_backend_unset}
    max-size-gb: ${KMDAH_CACHE_MAX_SIZE_GB:100}

    filesystem:
      root-dir: ${KMDAH_CACHE_FILESYSTEM_ROOT_DIR:}

  geoip:
    enabled: ${KMDAH_GEOIP_ENABLED:false}
    license-key: ${KMDAH_GEOIP_LICENSE_KEY:unset}

  gossip:
    id-generation-strategy: ${KMDAH_GOSSIP_ID_GENERATION_METHOD:random_uuid}
    redis:
      host: ${KMDAH_GOSSIP_REDIS_HOST:localhost}
      port: ${KMDAH_GOSSIP_REDIS_PORT:6379}
      gossip-topic: ${KMDAH_GOSSIP_REDIS_TOPIC:kmdah}
      lock-registry-key: ${KMDAH_GOSSIP_REDIS_LOCK_REGISTRY_KEY:kmdah-leadership}

  k8s:
    tls-secret:
      auto-update: ${KMDAH_K8S_TLS_SECRET_AUTO_UPDATE:false}
      name: ${KMDAH_K8S_TLS_SECRET_NAME:secret-name}
      namespace: ${KMDAH_K8S_TLS_SECRET_NAMESPACE:default}

  mangadex:
    client-secret: ${KMDAH_MANGADEX_CLIENT_SECRET:asuka>rei}
    load-balancer-ip: ${KMDAH_MANGADEX_LOAD_BALANCER_IP:unset}

  worker:
    port: ${KMDAH_WORKER_PORT:8080}
    bandwidth-mbps: ${KMDAH_WORKER_BANDWIDTH_MBPS:100}
