spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${kmdah.database.host}:${kmdah.database.port}/${kmdah.database.database}
    username: ${kmdah.database.user}
    password: ${kmdah.database.password}
