management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /__mon
      exposure.include:
        - info
        - health
        - prometheus

  metrics:
    web.client.request.autotime.enabled: false
