logging:
  level:
    root: INFO
    org.hibernate: WARN

spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${kmdah.database.host}:${kmdah.database.port}/${kmdah.database.database}
    username: ${kmdah.database.user}
    password: ${kmdah.database.password}

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /__mon
      exposure.include:
        - info
        - health
        - prometheus

  metrics:
    web.client.request.autotime.enabled: false

kmdah:
  version: @project.version@
  metadata:
    client-spec: 16
    server-header: kube-mdah ${kmdah.version} - ${spring.application.name} - https://github.com/Tristan971/kube-mdah

server:
  shutdown: graceful
  server-header: ${kmdah.metadata.server-header}
