kmdah:
  mangadex:
    client-secret: ${KMDAH_MANGADEX_CLIENT_SECRET:super-very-mega-secret}
    graceful-shutdown-seconds: ${KMDAH_MANGADEX_GRACEFUL_SHUTDOWN_SECONDS:300}

  operator:
    port: ${KMDAH_OPERATOR_PORT:8080}
    ping-frequency-seconds: ${KMDAH_OPERATOR_PING_FREQUENCY_SECONDS:15}
    workers-uri: ${KMDAH_OPERATOR_WORKERS_URI:http://localhost:${kmdah.worker.port}}
    tls-secret:
      namespace: ${KMDAH_OPERATOR_TLS_SECRET_NAMESPACE:default}
      name: ${KMDAH_OPERATOR_TLS_SECRET_NAME:mangadex-at-home-tls-secret}

  worker:
    port: ${KMDAH_WORKER_PORT:8081}
    operator-uri: ${KMDAH_WORKER_OPERATOR_URI:http://localhost:${kmdah.operator.port}}
    bandwidth-mbps: ${KMDAH_WORKER_BANDWIDTH_MBPS:100}
    verify-referrer: ${KMDAH_WORKER_VERIFY_REFERRER:true}

  cache:
    max-size-gb: ${KMDAH_CACHE_MAX_SIZE_GB:200}
    bucket-name: ${KMDAH_CACHE_BUCKET_NAME:kmdah-test}
    s3-auth:
      service-uri: ${KMDAH_CACHE_S3_AUTH_SERVICE_URI:https://kmdah-test.s3.fr-par.scw.cloud}
      signing-region: ${KMDAH_CACHE_S3_AUTH_SERVICE_REGION:fr-par}
      access-key-id: ${KMDAH_CACHE_S3_AUTH_ACCESS_KEY_ID}
      secret-access-key: ${KMDAH_CACHE_S3_AUTH_SECRET_ACCESS_KEY}
