spring:
  application:
    name: kmdah-worker
    version: @project.version@

  profiles:
    include:
      - commons
      - logging
      - metrics
      - persistence

server:
  port: ${kmdah.worker.port}
  shutdown: graceful
