logging.level:
  root: WARN
  moe.tristan.kmdah: INFO

server:
  shutdown: graceful
  port: ${kmdah.worker.port}
  server-header: kube-mdah ${spring.application.version} - ${spring.application.name} - https://github.com/Tristan971/kube-mdah

spring:
  application:
    name: kmdah-worker
    version: @project.version@
  task.scheduling.pool.size: 4
  mvc:
    contentnegotiation:
      favor-path-extension: true

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    enabled-by-default: true
    web:
      base-path: /__mon
      exposure.include:
        - info
        - health
        - prometheus

  metrics.web.client.request.autotime.enabled: false
