spring:
  application:
    name: kmdah-worker

  profiles:
    include:
      - commons
      - logging
      - metrics
      - persistence
      - web

server:
  port: ${kmdah.worker.port}
  shutdown: graceful
