# Internal configuration
spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    spec: @mangadex.spec@

server:
  port: ${kmdah.operator.port}
  shutdown: graceful
  server-header: kube-mdah ${spring.application.version} (${spring.application.spec}) - ${spring.application.name} - github.com/Tristan971/kube-mdah

logging.level:
  root: WARN
  moe.tristan.kmdah: INFO

management:
  endpoint.health.show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /__mon
      exposure.include:
        - info
        - health
        - prometheus

  metrics.web.client.request.autotime.enabled: false

# User configuration
kmdah:
  worker:
    port: ${KMDAH_WORKER_PORT:8081}
    operator-uri: ${KMDAH_WORKER_OPERATOR_URI:http://localhost:8080}
    bandwidth-mbps: ${KMDAH_WORKER_BANDWIDTH_MBPS:100}

  s3:
    bucket-name: ${KMDAH_CACHE_BUCKET_NAME:kmdah-test}
    service-uri: ${KMDAH_CACHE_S3_AUTH_SERVICE_URI:https://kmdah-test.s3.fr-par.scw.cloud}
    signing-region: ${KMDAH_CACHE_S3_AUTH_SERVICE_REGION:fr-par}
    access-key-id: ${KMDAH_CACHE_S3_AUTH_ACCESS_KEY_ID:fake-access-key}
    secret-access-key: ${KMDAH_CACHE_S3_AUTH_SECRET_ACCESS_KEY:fake-secret-key}
