name: Build and test

on: [ push ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '16'
          architecture: x64
          source: "https://download.java.net/java/early_access/loom/9/openjdk-16-loom+9-316_linux-x64_bin.tar.gz"
          archiveExtension: ".tar"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn -Drevision=$(cat version) -B package

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud
          username: tristandeloche
          password: ${{ secrets.SCW_SECRET_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            tristandeloche/kmdah:latest
            tristandeloche/kmdah:0.3.0-SNAPSHOT
            rg.fr-par.scw.cloud/tristandeloche/kmdah:latest
            rg.fr-par.scw.cloud/tristandeloche/kmdah:0.3.0-SNAPSHOT
